verbose: false
instrumentation:
  default-excludes: true
  excludes:
    - styles/**
    - public/**
    - tests/**
    - coverage/**
    - lib/**
    - webpack/**
    - config/**
    - src/server/db/migrations/**
    - src/server/db/models/**
    - src/shared/utils/semantic-custom.js
    - src/vendor/**
reporting:
  print: summary
  reports:
    - lcov
  dir: ./coverage
