verbose: false
instrumentation:
  root: src
  default-excludes: true
  excludes: [
    "server/webpack-stats.json",
    "styles",
    "public",
    "tests",
    "coverage",
    "lib",
    "webpack",
    "config"]
reporting:
    print: summary
    reports:
        - lcov
    dir: ./coverage
    watermarks:
        statements: [50, 80]
        lines: [50, 80]
        functions: [50, 80]
        branches: [50, 80]
