language: node_js
node_js:
  - "0.12.9"
  - "4"
  - "5"
  - "6"
sudo: false
script: npm run test:ci
after_success:
  - ./node_modules/.bin/codeclimate-test-reporter < coverage/lcov.info
  - cat coverage/lcov.info | ./node_modules/.bin/coveralls
  - rm -rf coverage
