language: node_js
node_js:
  - "iojs-v2.2.1"
script: DEBUG=* npm run test-ci
after_script:
  - codeclimate < coverage/lcov.info
  - cat coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - rm -rf coverage
