language: node_js
node_js:
  - "iojs-v2.3.4"
  - "0.12.7"
script: npm run test:ci
after_success:
  - codeclimate < coverage/lcov.info
  - cat coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - rm -rf coverage
